BuildMyPC/BuildMyPC/Models/Motherboard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace BuildMyPC.Models
{
    public class Motherboard
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(40)]
        public string Name { get; set; }
        [Required]
        public Brand Brand { get; set; }
        public int BrandId { get; set; }
        [Required]
        public string Socket { get; set; }
        public string FormFactor { get; set; }
        [Range(1, 128)]
        public int MaxRAM { get; set; }
        [Range(1, 10000)]
        public double Price { get; set; }
       
        
    }
}

BuildMyPC/BuildMyPC/Controllers/MotherboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using BuildMyPC.Models;

namespace BuildMyPC.Controllers
{
    public class MotherboardController : Controller
    {
        private ApplicationDbContext _context;

        public MotherboardController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Motherboard
        public ActionResult Index()
        {
            var motherboard = _context.Motherboards.ToList();

            return View(motherboard);
        }

        public ActionResult Details(int id)
        {

            var motherboards = _context.Motherboards.Include(c => c.Brand).SingleOrDefault(c => c.Id == id);
            if (motherboards == null)
                return HttpNotFound();

            return View(motherboards);
        }

        public ActionResult Addmotherboard(Motherboard motherboard)
        {
            Session["motherboard"] = motherboard;
            Session["motherboardname"] = motherboard.Name;

            return RedirectToAction("List", "Home");
        }
    }
}

BuildMyPC/BuildMyPC/Views/Motherboard/Details.cshtml
@model BuildMyPC.Models.Motherboard
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>@Model.Name</h3>
<ul>
    <li>Brand: @Model.Brand.BrandName</li>
    <li>Socket: @Model.Socket</li>
    <li>Form Factor: @Model.FormFactor</li>
    <li>Max RAM: @Model.MaxRAM GB</li>
    <li>Price: $@Model.Price</li>
</ul>

@Html.ActionLink("Back to List", "Index", "Motherboard")

BuildMyPC/BuildMyPC/Views/Motherboard/Index.cshtml
@model IEnumerable<BuildMyPC.Models.Motherboard>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Select a Motherboard</h2>

@if (!Model.Any())
{
    <p>There are no Cases availble.</p>
}

else
{

    <table class="table table-dark table-hover">
        <thread>
            <tr>
                <th>Motherboards (Click for Details)</th>
                <th>Socket</th>
                <th>Form Factor</th>
                <th>Max RAM</th>
                <th>Price</th>
                <th>Action</th>


            </tr>
        </thread>
        <tbody>

            @foreach (var motherboards in Model)
            {
                <tr>
                    <td>@Html.ActionLink(motherboards.Name, "Details", "Motherboard", new { id = motherboards.Id }, null)</td>
                    <td>@motherboards.Socket</td>
                    <td>@motherboards.FormFactor</td>
                    <td>@motherboards.MaxRAM GB</td>
                    <td>$@motherboards.Price</td>
                    <td>@Html.ActionLink("Add Motherboard", "Addmotherboard", "Motherboard", motherboards, null)</td>

                </tr>
            }
        </tbody>
    </table>









}