BuildMyPC/BuildMyPC/Models/CPU.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace BuildMyPC.Models
{
    public class CPU
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(40)]
        public string Name { get; set; }
        [Required]
        public Brand Brand { get; set; }
        public int BrandId { get; set; }
        [Range(1 ,10)]
        public double Speed { get; set; }
        [Range(1 ,32)]
        public byte Cores { get; set; }
        [Range(1, 1000)]
        public int PowerConsumption { get; set; }
        [Range(1, 10000)]
        public double Price { get; set; }
    }
}

BuildMyPC/BuildMyPC/Controllers/CPUController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using BuildMyPC.Models;

namespace BuildMyPC.Controllers
{
    public class CPUController : Controller
    {
        private ApplicationDbContext _context;

        public CPUController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: CPU
        public ActionResult Index()
        {

            var cpus = _context.CPUS.ToList();

            return View(cpus);
        }

        public ActionResult Details(int id)
        {
            
            var cpus = _context.CPUS.Include(c => c.Brand).SingleOrDefault(c => c.Id == id);
            if (cpus == null)
                return HttpNotFound();

            return View(cpus);
        }
        
        public ActionResult AddCpu(CPU cpu)
        {
            Session["Cpu"] = cpu;
            Session["Cpuname"] = cpu.Name;

            return RedirectToAction("List", "Home");
        }



    }
}

BuildMyPC/BuildMyPC/Views/CPU/Details.cshtml
@model BuildMyPC.Models.CPU
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>@Model.Name</h3>
<ul>
    <li>Brand: @Model.Brand.BrandName</li>
    <li>Core Speed: @Model.Speed GHz</li>
    <li>Cores: @Model.Cores</li>
    <li>Power Consumption: @Model.PowerConsumption W</li>
    <li>Price: $@Model.Price</li>
</ul>

@Html.ActionLink("Back to List", "Index", "CPU")

BuildMyPC/BuildMyPC/Views/CPU/Index.cshtml
@model IEnumerable<BuildMyPC.Models.CPU>

@{
                /**/

                ViewBag.Title = "Index";
                Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Select CPU</h2>

@if (!Model.Any())
{
    <p>There are no CPUs availble.</p>
}

else
{

<table class="table table-dark table-hover">
    <thread>
        <tr>
            
            <th>CPU (Click for Details)</th>
            <th>Speed</th>
            <th>Cores</th>
            <th>Price</th>
            <th>Action</th>
            
            
        </tr>
    </thread>
    <tbody>
       
                        @foreach (var cpu in Model)
                        {
        <tr>
           
            <td>@Html.ActionLink(cpu.Name, "Details", "CPU", new { id = cpu.Id }, null)</td>
            <td>@cpu.Speed GHz</td>
            <td>@cpu.Cores</td>
            <td>$@cpu.Price </td>

                       
            
           <td>@Html.ActionLink("Add Cpu", "AddCpu", "CPU", cpu, null)</td>

        </tr>
                        }
    </tbody>
</table>









}