BuildMyPC/BuildMyPC/Models/Case.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace BuildMyPC.Models
{
    public class Case
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(40)]
        public string Name { get; set; }
        [Required]
        public Brand Brand { get; set; }
        public int BrandId { get; set; }
        [Required]
        [MaxLength(10)]
        public string TowerType { get; set; }
        public bool ComesWithPowerSupply { get; set; }
        [Range(1, 1000)]
        public double Price { get; set; }

    }
}

BuildMyPC/BuildMyPC/Controllers/CaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using BuildMyPC.Models;

namespace BuildMyPC.Controllers
{
    public class CaseController : Controller
    {

        private ApplicationDbContext _context;

        public CaseController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Case
        public ActionResult Index()
        {

            var cases = _context.Cases.ToList();

            return View(cases);
        }

        public ActionResult Details(int id)
        {

            var cases = _context.Cases.Include(c => c.Brand).SingleOrDefault(c => c.Id == id);
            if (cases == null)
                return HttpNotFound();

            return View(cases);
        }

        public ActionResult AddCase(Case cases)
        {
            Session["cases"] = cases;
            Session["casesname"] = cases.Name;

            return RedirectToAction("List", "Home");
        }
    }
}

BuildMyPC/BuildMyPC/Views/Case/Details.cshtml
@model BuildMyPC.Models.Case
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>@Model.Name</h3>
<ul>
    <li>Brand: @Model.Brand.BrandName</li>
    <li>Tower Type: @Model.TowerType</li>
    <li>Comes with PSU? @Model.ComesWithPowerSupply</li>
    <li>Price: $@Model.Price</li>
</ul>

@Html.ActionLink("Back to List", "Index", "Case")

BuildMyPC/BuildMyPC/Views/Case/Index.cshtml
@model IEnumerable<BuildMyPC.Models.Case>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Select a Case</h2>

@if (!Model.Any())
{
    <p>There are no Cases availble.</p>
}

else
{

    <table class="table table-dark table-hover">
        <thread>
            <tr>
                <th>Cases (Click for Details)</th>
                <th>Tower Type</th>
                <th>Comes with PowerSupply</th>
                <th>Price</th>
                <th>Action</th>


            </tr>
        </thread>
        <tbody>

            @foreach (var cases in Model)
            {
                <tr>
                    <td>@Html.ActionLink(cases.Name, "Details", "Case", new { id = cases.Id }, null)</td>
                    <td>@cases.TowerType</td>
                    <td>@cases.ComesWithPowerSupply</td>
                    <td>$@cases.Price </td>
                    <td>@Html.ActionLink("Add Case", "AddCase", "Case",cases, null)</td>

</tr>
            }
        </tbody>
    </table>









}